# Generated by Django 6.0.7 on 2026-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/audio/'),
        ),
    ]
