# Generated by Django 6.0.7 on 2026-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('SECURITY', 'Security Alert'), ('ACCESS_DENIED', 'Access Denied'), ('VERIFY', 'Verification'), ('VIEW', 'View')], max_length=20),
        ),
    ]
